### ISSUE TITLE
c++14 and vex::Filter compile issues

### ISSUE THREAD

**Issue by lajash** [ddemidov/vexcl#159]
Hi Denis,

Filter code that compiles with c++11 on Clang suddenly gives tuple rvalue reference errors under c++14.
e.g.

vex::Filter::General filter = vex::Filter::Any;
filter = filter && vex::Filter::DoublePrecision;

Compile error:
../include/c++/v1/tuple:267:11: error: rvalue reference to type 'vex::Filter::General' cannot bind to lvalue of type 'vex::Filter::General'
        : value(__t.get())

I'm compiling on Mac OsX Yosemite, Apple Clang 3.5 .

Thanks,
Rajesh.

**Comment by lajash** [comment]
Not sure if this is related .... http://llvm.org/bugs/show_bug.cgi?id=19118

**Comment by ddemidov** [comment]
Could you please provide a minimal failing code? The following compiles for me with clang 3.5.1 both with `-std=c++1y` and `-std=c++14`:
~~~cpp
#include <iostream>
#include <vexcl/vexcl.hpp>

int main() {
    vex::Filter::General f = vex::Filter::Env;
    f = f && vex::Filter::DoublePrecision;
    vex::Context ctx(f);
    std::cout << ctx << std::endl;
}
~~~

Also, if this does not work, could you provide full compiler output? (as gist if too big).

**Comment by ddemidov** [comment]
Yes, the bugreport seems to be related. If that is the case, could you try it with recent clang?

**Comment by lajash** [comment]
You're right ... it works fine on Clang 3.5.2 but barfs in apple-clang provided with Xcode 6.1. I think its of svn version 3.5 but prior to when this fix was rolled in. I guess I'll have to upgrade the compiler or wait for Xcode's next upgrade.... grrrr .....
