### ISSUE TITLE
Type casting

### ISSUE THREAD

**Issue by borissmidt** [ddemidov/vexcl#160]
Is there a way to cast types in VexCL?
 since it isn't listed in the documentation.

**Comment by ddemidov** [comment]
What exactly do you mean by type casting?

**Comment by borissmidt** [comment]
i have done some calculations on a vector of floats on the gpu.
But i need to cast it to an integer so i can use it as a pointer later on.

**Comment by ddemidov** [comment]
OpenCL has [convert](https://www.khronos.org/registry/cl/sdk/1.1/docs/man/xhtml/convert_T.html) family of functions that you could use:
~~~{.cpp}
vex::vector<int> a(ctx, n);
vex::vector<float> b(ctx, n);
b = convert_float(a) / 2;
~~~
 Or, if you want to be able to switch backends between OpenCL and CUDA, you could introduce your own function:
~~~{.cpp}
VEX_FUNCTION(float, make_float, (int, i),
    return (float)i;
    );
b = make_float(a) / 2;
~~~

**Comment by borissmidt** [comment]
thanks for the answere and fast response. 
Maybe you could add this to your git readme? i will now close this issue.

**Comment by ddemidov** [comment]
I am not sure of where exactly to put this in the README, so let's hope this issue will help to anyone with a similar problem in the future. Feel free to make a pull request with the documentation change if you have a better idea :).

**Comment by borissmidt** [comment]
Are the functions "vex::convert_XXX" backend independent? then i could add it to the read me.
if not then i think the best spot for the read me is just after the user-defined-functions sections. So the user know he can make functions an thus he can use it for type casting/ conversion. 

### <a name="type-casting"></a>Type casting

Type casting a vector can be done by using the [TypeCasting][] family of functions
[TypeCasting]: https://www.khronos.org/registry/cl/sdk/1.1/docs/man/xhtml/convert_T.html
~~~{.cpp}
vex::vector<int> a(ctx, n);
vex::vector<float> b(ctx, n);
b = convert_float(a) / 2;
~~~
An other option is to define a function. This has the advantage of beeing backend independent. 
~~~{.cpp}
VEX_FUNCTION(float, make_float, (int, i),
    return (float)i;
    );
b = make_float(a) / 2;
~~~

**Comment by ddemidov** [comment]
`convert_***` functions are buitin OpenCL functions, so they are not available for CUDA. The fact that users can use custom functions for this purpose seems too obvious for me to include it into the README, but may be I am a bit biased being the library developer :). I think including your second example into the end of `User-defined functions` section could be a good idea. Would you like to do a pull request?

**Comment by borissmidt** [comment]
i have created a pull request , i hope i done it right since it is the first time i do a a pull request. 
did i really have to create a fork or was that completely unnecessary?

**Comment by ddemidov** [comment]
I made some notes there.

> did i really have to create a fork or was that completely unnecessary?

Yes, creating a fork is how you supposed to do pull requests on github.
