### ISSUE TITLE
expected kernel call overhead

### ISSUE THREAD

**Issue by borissmidt** [ddemidov/vexcl#162]
This isn't really an issue.

But i am wondering how much function call overhead we should expect using VexCL and an OpenCL backend? 

My measurements gave me something between 70ms-200ms overhead for a simple function with a small data size. i am working on linux mint with an amd gpu.

**Comment by ddemidov** [comment]
I never really measured this kind of data, as I am more interested in kernels with huge amounts of data, where any possible overhead is hidden by the actual computations. But [this](https://gist.github.com/1dd5e76780f47a64920c) simple test shows that a kernel launch (with a subsequent clFinish() call) costs about 1e-05 sec on a Tesla K40c and 5e-6 sec on an AMD FirePro W9100.

**Comment by borissmidt** [comment]
Thx, it seems that the latency is somewhere in my own code. The overhead in your test is very small after the first run.

**Comment by borissmidt** [comment]
it seems that my kernel doesn't get cached. all kernel runs take >150 ms even with small amounts of data. 

i think i found the problem, i reinitialize the ctx every time, this forces the program to remake the program. I will now make the context a private variable of mine class and test it again.

**Comment by borissmidt** [comment]
it seems to work. My calculations are now much faster since the kernel doesn't need to be recompiled. Many thanks.

**Comment by ddemidov** [comment]
That is correct: when context is destroyed, all kernel caches associated with it are purged automatically.
