### ISSUE TITLE
Error with Kernel / Profiler hpps

### ISSUE THREAD

**Issue by misterarduino** [ddemidov/vexcl#164]
Dear Denis, 

I've been scratching my head over compiler errors in the compilation of any file that contains the vexcl.hpp, in VS 2013 W8.1 64b. 

1>------ Build started: Project: Project1, Configuration: Debug Win32 ------
1>  Source.cpp
1>c:\program files (x86)\amd app sdk\2.9-1\include\vexcl\backend\opencl\kernel.hpp(174): error C2589: '(' : illegal token on right side of '::'
1>c:\program files (x86)\amd app sdk\2.9-1\include\vexcl\backend\opencl\kernel.hpp(174): error C2059: syntax error : '::'
1>c:\program files (x86)\amd app sdk\2.9-1\include\vexcl\util.hpp(36): fatal error C1189: #error :  Please define NOMINMAX macro globally in your project
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

I understand that this MINMAX error is related to the min/max problem in C++ and Windows, however, I tried to implemented the std namespace on those files and modified the std::min/max to min/max without namespace, but I'm still getting this frustrating error. 

Do you have any suggestion? 

Thanks, 

Marko

**Comment by ddemidov** [comment]
As the error message indicates, you need to define NOMINMAX macro globally. I don't remember where exactly this is done in Visual Studio (somewhere in project properties), but here is what I do in cmake project file: https://github.com/ddemidov/vexcl/blob/master/CMakeLists.txt#L82

**Comment by ddemidov** [comment]
Found a random pic from the internets:

![](http://www.softelvdm.com/Docs2/SftTree%20DLL%207.0/image/usingc3_vsnet.gif)

**Comment by kgnk** [comment]
Frequently, I just `#undef` `min` and `max` after including `windows.h`.

**Comment by ddemidov** [comment]
@misterarduino, did either of those suggestions work for you?
