### ISSUE TITLE
POCL's OPENCL_DEVICE_TYPE_CPU | OPENCL_DEVICE_TYPE_DEFAULT is not found when filtering for CPU devices

### ISSUE THREAD

**Issue by rubenvb** [ddemidov/vexcl#170]
When [POCL](www.portablecl.org) is installed (using the [ocl-icd](https://forge.imag.fr/projects/ocl-icd/)), I cannot create a vexcl device context for it when filtering on `CL_DEVICE_TYPE_CPU`, although I'm guessing it should. Looking at the filter code in vexcl, it seems you're handling compound device types correctly. I tested with NVIDIA's, Khronos' and ocl-icd, and clinfo reports an empty device type string for pocl in all cases, so I doubt this is an ICD problem. I'm hoping you may be able to shed more light on this.

See for reference: https://github.com/pocl/pocl/issues/168

**Comment by ddemidov** [comment]
I've updated examples/devlist.cpp to output device type, and it shows that POCL device is indeed `OPENCL_DEVICE_TYPE_CPU | OPENCL_DEVICE_TYPE_DEFAULT`.  I think this is a bug in `vex::Filter::Type()` that should be fixed in 40460c5.

**Comment by ddemidov** [comment]
But the filter did work for me when I explicitly asked for `OPENCL_DEVICE_TYPE_CPU | OPENCL_DEVICE_TYPE_DEFAULT`:
```cpp
    vex::Context ctx(vex::Filter::Type(OPENCL_DEVICE_TYPE_CPU | CL_DEVICE_TYPE_DEFAULT));
    std::cout << ctx << std::endl;
```

**Comment by rubenvb** [comment]
Awesome! Thanks for the extremely quick response!
But... shouldn't a bitmask like CL_DEVICE_TYPE be created with `|` but checked for content with `&`?

**Comment by ddemidov** [comment]
Of course you are right. Thanks for pointing this out!

**Comment by rubenvb** [comment]
I have verified your fix works for me. Awesome work on VexCL, I appreciate your effort and find it a very pleasant alternative to, well, using CUDA/OpenCL directly.
