### ISSUE TITLE
Vexcl compilation error with OpenCL for viennaCL tutorial problem

### ISSUE THREAD

**Issue by ahazra** [ddemidov/vexcl#173]
I tried to compile the ViennaCL tutorial program solvers.cpp with
g++ -DVEXCL_BACKEND_OPENCL -std=c++11 solvers.cpp  -I/HOME/ahazra/libraries/include -L/HOME/ahazra/libraries/lib -lOpenCL -lboost_system

I found an error

In instantiation of ‘VectorT viennacl::linalg::solve(const MatrixT&, const VectorT&, const viennacl::linalg::cg_tag&, const PreconditionerT&) [with MatrixT = vex::SpMat<double>; VectorT = vex::vector<double>; PreconditionerT = viennacl::linalg::no_precond]’:
/HOME/ahazra/libraries/include/viennacl/linalg/cg.hpp:470:64:   required from ‘VectorT viennacl::linalg::solve(const MatrixT&, const VectorT&, const viennacl::linalg::cg_tag&) [with MatrixT = vex::SpMat<double>; VectorT = vex::vector<double>]’
solvers.cpp:15:60:   required from ‘void do_solve(const vex::SpMat<double>&, vex::vector<double>, const Tag&) [with Tag = viennacl::linalg::cg_tag]’
solvers.cpp:83:57:   required from here
/HOME/ahazra/libraries/include/viennacl/linalg/cg.hpp:446:5: error: could not convert ‘boost::proto::exprns_::operator==(Left&&, Right&&) [with Left = const vex::vector_expression<boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::address_of, boost::proto::argsns_::list1<vex::vector<double>&>, 1l> >; Right = const vex::vector_expression<boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::address_of, boost::proto::argsns_::list1<vex::vector<double>&>, 1l> >; typename boost::proto::detail::enable_binary<boost::proto::domainns_::deduce_domain, boost::proto::detail::not_a_grammar, boost::mpl::or_<boost::proto::is_extension<Arg>, boost::proto::is_extension<Right> >, boost::proto::tagns_::tag::equal_to, const Left&, const Right&>::type = vex::vector_expression<boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::equal_to, boost::proto::argsns_::list2<vex::vector_expression<boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::address_of, boost::proto::argsns_::list1<vex::vector<double>&>, 1l> >, vex::vector_expression<boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::address_of, boost::proto::argsns_::list1<vex::vector<double>&>, 1l> > >, 2l> >]((* & boost::proto::exprns_::operator&(Arg&&) [with Arg = vex::vector<double>&; typename boost::proto::detail::enable_unary<boost::proto::domainns_::deduce_domain, boost::proto::detail::not_a_grammar, boost::proto::is_extension<Arg>, boost::proto::tagns_::tag::address_of, const Arg&>::type = vex::vector_expression<boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::address_of, boost::proto::argsns_::list1<vex::vector<double>&>, 1l> >]()))’ from ‘const type {aka const vex::vector_expression<boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::equal_to, boost::proto::argsns_::list2<vex::vector_expression<boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::address_of, boost::proto::argsns_::list1<vex::vector<double>&>, 1l> >, vex::vector_expression<boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::address_of, boost::proto::argsns_::list1<vex::vector<double>&>, 1l> > >, 2l> >}’ to ‘bool’
     if (&residual==&z)
     ^
Would anyone plesase help me to solve this problem? Thank you in advance.

**Comment by ddemidov** [comment]
This should be fixed in viennacl/viennacl-dev#131. You should pull the latest viennacl master branch.

Keep in mind though that the example uses simple unpreconditioned CG/BiCGStab solver. If you want a better solver, you could try [amgcl](https://github.com/ddemidov/amgcl), which has backends for both viennacl and vexcl libraries.
