### ISSUE TITLE
Is runtime backend selection possible?

### ISSUE THREAD

**Issue by rubenvb** [ddemidov/vexcl#174]
Would it be possible to make the backend a runtime thing, so that e.g. a VeXCL CPU device running on OpenCL can be used "together" (as in, at the same time) with a CUDA device?

Additionally, the current setup needs to seperate binaries for CUDA and OpenCL, if I'm not mistaken. I frankly don't know how both backends compare wrt performance of the generated code, so this may well be a non-issue after all. Still, it would be interesting to have this possibility I think!

**Comment by ddemidov** [comment]
Backend selection is a compile-time decision. You can not even isolate different backends into separate binary modules, as there will be conflicts at the time of linking. Still, NVIDIA does support OpenCL, so you can use both a CPU and a CUDA device with OpenCL backend.

It should be easy to compare backend performance with either provided examples/benchmark.cpp or a manually written one tailored to your specific needs.
