### ISSUE TITLE
Is there any example of Finite Difference Method GPU code using vexcl?

### ISSUE THREAD

**Issue by ahazra** [ddemidov/vexcl#175]
I am new user of GPU and vexcl.I am looking for an example of a simple Finite Difference code using vexcl as I do not have much time to go into much detail. It would be great if I get some sort of template or just an elementary example.

**Comment by ddemidov** [comment]
https://github.com/ddemidov/amgcl/blob/master/examples/vexcl.cpp is an example of solving 3D Poisson problem with AMG and vexcl. The problem is discretized with FDM here: https://github.com/ddemidov/amgcl/blob/master/tests/sample_problem.hpp

**Comment by ahazra** [comment]
Thank you a lot. I will check.

**Comment by ahazra** [comment]
I actually want to solve one advection equation of the following form using say upwind method. Would you give me some idea how can I use amgcl to solve that? or is there any example? 
![advection_eqn](https://cloud.githubusercontent.com/assets/11569555/7178069/31d2dcdc-e42c-11e4-9086-0ca3cf7a4e59.png)

**Comment by ddemidov** [comment]
You need to discretize your problem to get a linear system of equations, then use amgcl to solve it. The fact that you want to use GPUs is really irrelevant here.
