### ISSUE TITLE
Multi-vector related question

### ISSUE THREAD

**Issue by ahazra** [ddemidov/vexcl#176]
Hello,

I am newbie to GPU computing and learning to use vexcl library.

I just wanted to ask
1) what is the a way to copy a standard 2-d vector or eigen matrix or armadillo matrix to device to initialize a multi-vector in the device?

2) what is the a way to copy a multi-vector in device to another multi-vector in device?

3) what is the way to copy a multi-vector from to device back to standard 2-d vector or eigen matrix or armadillo matrix from device?

It would be really helpful if someone can help me out. Thank you in advance.

**Comment by ahazra** [comment]
I just checked after that. I guess I can use viennacl to do all these stuff. 
Is there anything to add if not then I guess this issue is useless. Sorry to bother.

**Comment by ddemidov** [comment]
`vex::multivector` is not intended to be used as a dense matrix. It is simply a statically sized collection of 1D vectors. Hence, the memory is not continuous, and you need to copy it row-wise. Individual vector components may be accessed with `multivector::operator()` (see [README](https://github.com/ddemidov/vexcl#multivectors) for details). You can use `vex::copy()` with those.

If you need a dynamically sized 2D matrix of size [n x m], you are probably better off with a continuously stored `vex::vector(ctx, n * m)`. You can then access individual rows/columns with [slices](https://github.com/ddemidov/vexcl#slicing).

> 2) what is the a way to copy a multi-vector in device to another multi-vector in device?

This is as simple as
```cpp
mv1 = mv2;
```

If your problem involves a lot of dense algebra operations, then viennacl may indeed be a better option.
