### ISSUE TITLE
Mark boost libraries as REQUIRED in CMakeLists.txt

### ISSUE THREAD

**Issue by torquil** [ddemidov/vexcl#179]
The initial 'cmake' run before 'make' finishes without warnings even if the various boost libraries are not found. As I understand it, these are required, because my first vexcl build attempt failed because these were missing. However, the cmake behaviour can be improved by changing line 83 in the top-level CMakeLists.txt from

find_package(Boost COMPONENTS ${VEXCL_BOOST_COMPONENTS})

to

find_package(Boost REQUIRED COMPONENTS ${VEXCL_BOOST_COMPONENTS})

With this change, cmake will inform the user about the missing boost libraries, instead of the user getting build errors when subsequently running 'make'.

**Comment by ddemidov** [comment]
Thanks for spotting! Are you willing to make a pull request for this?

**Comment by ddemidov** [comment]
Fixed in #180
