### ISSUE TITLE
reductor.hpp missing vexcl/vector.hpp?

### ISSUE THREAD

**Issue by torquil** [ddemidov/vexcl#181]
My program will only compile if I include vexcl/vector.hpp above vexcl/reductor.hpp. Otherwise, I get:

/home/tmac/usr/include/vexcl/reductor.hpp: In member function ‘typename std::enable_if<boost::proto::matches<Expr, vex::vector_expr_grammar>::value, real>::type vex::Reductor<real, RDC>::operator()(const Expr&) const’:
/home/tmac/usr/include/vexcl/reductor.hpp:288:21: error: ‘partition’ is not a member of ‘vex’
         prop.part = vex::partition(prop.size, queue);

Perhaps reductor.hpp is missing a vexcl/vector.hpp header?

Best regards
Torquil Sørensen

**Comment by ddemidov** [comment]
Thanks for catching this! Fixed by 75e8552.
