### ISSUE TITLE
Sort on multiple CPUs is slower than CPU

### ISSUE THREAD

**Issue by byzhang** [ddemidov/vexcl#184]
I recently ran benchmark on 5 Titan X and Xeon 2630V3.
And for CUDA, I got
```
Sort (ulong)
    VexCL:         637643 keys/sec
    STL:           2.30467e+06 keys/sec
```
Similar results for OpenCL,
```
Sort (ulong)
    VexCL:         627855 keys/sec
    STL:           2.25604e+06 keys/sec
```
It looks slower than a single Titan Black
```
Sort (ulong)
    VexCL:         4.76384e+08 keys/sec
    STL:           3.02633e+06 keys/sec
```
Is it expected, like caused by the communication among GPUs? 
If it's the case, is it possible to reduce the communication as there is 700 times difference?

**Comment by ddemidov** [comment]
The sort on multiple GPUs is done by first sorting each GPU's partition on that GPU, then merging the results on host (partitions are transfered to host, merged there, then pushed back to GPUs). The idea was that both transfer and the merge have linear performance, while sort is O(n log n), so some speedup could be gained from this. May be I was wrong.

**Comment by ddemidov** [comment]
Are the results you cite coming from vexcl benchmark? It could be the [sample size](https://github.com/ddemidov/vexcl/blob/51145fa228b4d6321d5ff0a34ff09d2498cbfdf6/examples/benchmark.cpp#L673) is too small to see speedup on 5 GPUs. Can you try and increase the vector size?

**Comment by byzhang** [comment]
Yes, it's from vexcl benchmark. I changed to 256M elements, but now it has
been about 30 minutes, and it's still running, so it seems already slower
than CPU. I'll update once it's done.

Thanks,
-B

**Comment by byzhang** [comment]
Same speed for 256M elements:

Sort (ulong)
    VexCL:         633868 keys/sec

Thanks,
-B

**Comment by ddemidov** [comment]
I tested this on a system with 3 Tahiti GPUs. Here are the results for 1, 2, and 3 GPUs:
```
1. Tahiti (AMD Accelerated Parallel Processing)

Sort (ulong)
    VexCL:         5.48828e+08 keys/sec
    STL:           1.50473e+07 keys/sec
Sort (uint)
    VexCL:         1.09647e+09 keys/sec
    STL:           1.50623e+07 keys/sec

1. Tahiti (AMD Accelerated Parallel Processing)
2. Tahiti (AMD Accelerated Parallel Processing)

Sort (ulong)
    VexCL:         7.7413e+07 keys/sec
    STL:           1.50535e+07 keys/sec
Sort (uint)
    VexCL:         9.79374e+07 keys/sec
    STL:           1.5062e+07 keys/sec

1. Tahiti (AMD Accelerated Parallel Processing)
2. Tahiti (AMD Accelerated Parallel Processing)
3. Tahiti (AMD Accelerated Parallel Processing)

Sort (ulong)
    VexCL:         6.62069e+07 keys/sec
    STL:           1.50446e+07 keys/sec
Sort (uint)
    VexCL:         7.96394e+07 keys/sec
    STL:           1.4895e+07 keys/sec
```
So performance does deteriorate with number of GPUs used, with the largest drop immediately between one and two GPUs. Unfortunately, I don't see a way to improve the multi-GPU performance here.

**Comment by byzhang** [comment]
As @ddemidov points out, I ran it in a debug version. 
Now it's,
```
Sort (ulong)
    VexCL:         3.69459e+07 keys/sec
    STL:           1.22751e+07 keys/sec
```
