### ISSUE TITLE
Using existing context in VexCL

### ISSUE THREAD

**Issue by apeternier** [ddemidov/vexcl#187]
Dear all,

a quick question: is it possible to tell VexCL to reuse an OpenCL context/device/queue already initialized by another library? 
It would be nice to have something similar to ViennaCL's  viennacl::ocl::setup_context() and viennacl::ocl::switch_context(), which take already initialized cl_context and cl_device_id objects as input. 

Thanks!

**Comment by ddemidov** [comment]
Absolutely, see #5.

**Comment by apeternier** [comment]
Great, thanks for the quick reply!
I'm trying to initialize a vex::Context through my cl_context and cl_command_queue, but I've a couple of problems.

I tried this (pardon me if my approach is naively wrong, I'm not very used to STL):

std::vector<std::pair<cl::Context, cl::CommandQueue>> customCtx;
// fill customCtx...
vex::Context ctx(customCtx);

But I'm getting a compile-time error (both under Windows and Linux):

(win) vexcl\include\vexcl/backend/opencl/context.hpp(179): error C2064: term does not evaluate to a function taking 1 arguments
(linux) vexcl/include/vexcl/backend/opencl/context.hpp|179|error: no match for call to ‘(std::vector<std::pair<cl::Context, cl::CommandQueue> >) (cl::Device&)’

What am I doing wrong?

**Comment by ddemidov** [comment]
You don't need to create an instance of `vex::Context` if you already have your own context and queue.
This should be enough:
```cpp
cl_command_queue my_queue; // Initialized elsewhere

std::vector<cl::CommandQueue> ctx = {cl::CommandQueue(my_queue)};
vex::vector<int> x(ctx, 1024);
```

But if you really want to create vex::Context, you should do it with a vector of cl contexts and a vector of queues:
```cpp
cl_context my_context;
cl_command_queue my_queue;

std::vector<cl::Context> c = {cl::Context(my_context)};
std::vector<cl::CommandQueue> q = {cl::CommandQueue(my_queue)};

vex::Context ctx(c, q);
```

**Comment by apeternier** [comment]
Thanks again, I'm using your first suggestion and now I can compile and run my code. 
But I'm now getting a 'std::runtime_error' with 'what(): Uninitialized static context' when I try to create an AMG object (yes, I'm using both your libraries: AMGCL with ViennaCL and VexCL as backends):

`AMG amg(amgcl::backend::map(cpuBmat));`

AMG is typedef'd as follows:

`typedef amgcl::amg<Backend,
        amgcl::coarsening::ruge_stuben,
        amgcl::relaxation::damped_jacobi> AMG;`

So I do need to have a full context initialized if I also involve AMGCL?

**Comment by ddemidov** [comment]
You need to specify backend parameters as follows:

```cpp
AMG::params prm;
Backend::params bprm;
brpm.q = ctx;

AMG amg(map(...), prm, bprm);
```

This is the one advantage of using `vex::Context`. When you create its instance, it stores reference to itself in a static variable. Then VexCL backend is able to pick that up automatically. Otherwise you have to provide queue list explicitly, as in the above example.

**Comment by apeternier** [comment]
I tried your approach but the compiler cannot find a constructor for AMG with three parameters (i.e., I can't append prm and bprm). I investigated a bit and tried this instead:

`iterationInfo::AMG::params prm;
 prm.backend.q = *reserved->vexCtx;
 iterationInfo::AMG amg(amgcl::backend::map(cpuBmat), prm);`

It compiles but I'm getting the same 'Uninitialized static context' error as before.

**Comment by ddemidov** [comment]
It looks like you are not using the latest amgcl, this has changed a couple
of months ago. This is how it looked on the latest tagged version :
https://github.com/ddemidov/amgcl/blob/0.6.4/examples/vexcl.cpp#L41
Cheers,
Denis

**Comment by apeternier** [comment]
Exactly, I'm using the last tagged version. Should I update to the master snapshot?

**Comment by ddemidov** [comment]
You don't have to, this should work there as well.

Cheers,
Denis

**Comment by ddemidov** [comment]
Creating full vexcl context (option two above) should help with static context error. I'll try to see what's happening there some time later.

**Comment by apeternier** [comment]
Thanks Denis, I will also try to play a bit with all the information you provided me today.
To be honest, under Windows I've everything working as expected, but under Linux I'm facing some issues. The code is physically the same, but there must be something wrong that I've to identify: at some point, the memory gets corrupted through simple viennacl/vexcl operations which are running fine under Windows. 

Cheers,
Achille

**Comment by ddemidov** [comment]
I can reproduce the issue. The problem is that the default constructor of `amgcl::backend::vexcl::params` requires that an instance of `vex::Context` was instantiated beforehand.  You can do that with your own context and queue, as was shown above. Here is a complete working example, based on `examples/vexcl.cpp` at tag 0.6.4:
https://gist.github.com/f39b582b7a171e772526

**Comment by apeternier** [comment]
Mmh, I'm facing a problem at the end of the application now, when I release the OpenCL context.
The problem seems to be related to the vtx::Context I created from given cl_context and cl_command_queue. 

I'm using my own library for creating the OpenCL context/device/queue and then I'm reusing these both in ViennaCL and VexCL. I suspect that vex::Context releases the queue and context I passed when I quit the application, but I already disposed of these resources in my library, so there's a double deallocation, and the second one fails because applied on an already released resource. 
By initializing vex::Context with a new context (using filters) instead of reusing the one created by my library, everything is fine. Am I doing something wrong?

Thanks,
Achille

**Comment by ddemidov** [comment]
Can you try to call clRetainContext and clRetainCommandQueue before passing
your context and queue to vex::Context constructor?

Cheers,
Denis

**Comment by apeternier** [comment]
It works, good hint. Is then something I've to do explicitly? Shouldn't be an implicit feature of a vex::Context created from existing handles? Thanks a lot.

**Comment by ddemidov** [comment]
`vex::Context` is created from `cl::Context` and `cl::CommandQueue` objects, which are part of C++ API. Those object do retaining in their copy constructors, so explicit retaining is not usually required. I seems as you are using pure C API though, so you have to do explicit retaining.

**Comment by ddemidov** [comment]
ddemidov/amgcl@c72e493 solves the 'Uninitialized static context' problem mentioned in https://github.com/ddemidov/vexcl/issues/187#issuecomment-156457752. Now you don't have to instantiate `vex::Context`, and may use approach showed in https://github.com/ddemidov/vexcl/issues/187#issuecomment-156438812.

I've checked that this works with the following patch to `amgcl/examples/vexcl.cpp`:
```diff
diff --git a/examples/vexcl.cpp b/examples/vexcl.cpp
index c6b82f4..657d11e 100644
--- a/examples/vexcl.cpp
+++ b/examples/vexcl.cpp
@@ -18,8 +18,15 @@ namespace amgcl {
 int main(int argc, char *argv[]) {
     using amgcl::prof;
 
+    /*
     vex::Context ctx( vex::Filter::Env );
     std::cout << ctx << std::endl;
+    */
+    cl::Context context(CL_DEVICE_TYPE_CPU);
+    std::vector<cl::Device> devices = context.getInfo<CL_CONTEXT_DEVICES>();
+    cl::CommandQueue queue(context, devices[0]);
+
+    std::vector<cl::CommandQueue> ctx = {queue};
 
     std::vector<int>    ptr;
     std::vector<int>    col;
```

**Comment by blackccpie** [comment]
Hi, I'm still getting some boost::compute / VexCL interoperability issues, like in the following code snippet where I'm getting some double deallocation crashes unless I explicitly call clRetainCommandQeue:

```
boost::compute::command_queue command_queue = ...; // using a boost::compute::context

std::vector<cl::CommandQueue> vex_ctx = { cl::CommandQueue( command_queue ) };
clRetainCommandQueue( command_queue.get() );

vex::vector<float> my_vector = vex::vector<float>( vex_ctx, ... );

```

Is there a way I can write this more elegantly?

Thanks for your help!

**Comment by ddemidov** [comment]
You have to do this (retain context explicitly), when vexcl is used with OpenCL backend. But you could eliminate some noise if you used vexcl with Boost.compute backend:

```cpp
#include <iostream>
#include <boost/compute.hpp>

// Select Boost.Compute backend (better to do this through compiler flags)
#define VEXCL_BACKEND_COMPUTE
#include <vexcl/vexcl.hpp>

int main() {
    boost::compute::command_queue bcq = boost::compute::system::default_queue();
    std::cout << bcq.get_device().name() << std::endl;

    // vex::backend::command_queue is boost::compute::command_queue
    // with Boost.Compute backend
    std::vector<vex::backend::command_queue> ctx = {bcq};

    vex::vector<int> x(ctx, 16);
    x = vex::element_index();

    std::cout << x << std::endl;
}
```

**Comment by ddemidov** [comment]
In fact, this works for me as well:
```cpp
    boost::compute::command_queue bcq = boost::compute::system::default_queue();
    vex::vector<int> x({bcq}, 16);
```

**Comment by ddemidov** [comment]
Note that you need ed96aaa2284fdab76faa1decfb478db24857a91b for boost.compute backend to work with boost 1.60.

**Comment by ddemidov** [comment]
https://gist.github.com/ddemidov/ff022cca11c7715ec1b7

**Comment by blackccpie** [comment]
I switched to Boost::Compute backend, and that did the trick indeed.

Thanks for the tip!

**Comment by Reneg973** [comment]
Hi Dennis,  I am playing around with vexcl to find out how much my
algorithms could get faster using Vexcl.  Unfortunately I am missing a lot
of things especially for reductions. I have modified the code to support
different output types e.g. for calculating sum of shorts without running
into overflows. Now I try to extend the reductor to combine different
operations into one kernel. But I run into problems with boost:: proto.

My simple question is, do you think it is possible to implement such a
thing?

Greetings,
René

**Comment by ddemidov** [comment]
Hi Rene, 

can you open a new  issue so we could discuss it there?
