### ISSUE TITLE
OpenCL 2.1 support

### ISSUE THREAD

**Issue by acterhd** [ddemidov/vexcl#188]
Hello. Will you support opencl 2.1 or not? 
I suggest made for nvidia and intel only, because AMD not planned support GPGPU.

**Comment by ddemidov** [comment]
OpenCL 2.1 specification was just released by Khronos, so its not supported by any vendor at this point. It should be backwards compatible though, so nothing should prevent you using VexCL with it when an implementation will become available. The kernels generated by VexCL are for the most part very simple and do not require any features not present in OpenCL 1.1.

**Comment by acterhd** [comment]
Will SVM or not?
25 нояб. 2015 г. 0:40 пользователь "Denis Demidov" <notifications@github.com>
написал:

**Comment by ddemidov** [comment]
> Will SVM or not?

I am sorry, I don't understand the question.

**Comment by acterhd** [comment]
Will SVM (shared virtual memory) support by VexCL?
25 нояб. 2015 г. 0:44 пользователь "Denis Demidov" <notifications@github.com>
написал:

**Comment by ddemidov** [comment]
I don't currently have plans on directly supporting shared virtual memory. That could still be used with custom kernels I think. Do you have a specific workflow in mind?

**Comment by acterhd** [comment]
I try create BVH with opencl. Sad SVM not available with opencl 1.2. I have
200 miliseconds with 5000 polygons.
25 нояб. 2015 г. 0:54 пользователь "Denis Demidov" <notifications@github.com>
написал:

**Comment by acterhd** [comment]
I have question. Do you planned support directx 12 compute shader?
25 нояб. 2015 г. 1:29 пользователь "Alexey Solovey" <acterhd@gmail.com>
написал:

**Comment by ddemidov** [comment]
> Do you planned support directx 12 compute shader?

No, I have no plans about that either. I have no experience with directx, but pull requests are always welcome.
