### ISSUE TITLE
How to use vex::vector with structures?

### ISSUE THREAD

**Issue by acterhd** [ddemidov/vexcl#190]
Hello. I have problem with vex::vector structures. How to use it?

**Comment by ddemidov** [comment]
This question from stackoverflow seems to be relevant:
http://stackoverflow.com/questions/30842071/vexcl-vector-of-structs

**Comment by acterhd** [comment]
I'm sorry. I have another problem.

2016-01-03 19:30 GMT+08:00 Denis Demidov <notifications@github.com>:
