### ISSUE TITLE
How to make unpartited vector array?

### ISSUE THREAD

**Issue by acterhd** [ddemidov/vexcl#191]
I'm sorry for previous question. I have another question: how to make full vector, without partition in devices?

**Comment by ddemidov** [comment]
You need to pass single command queue to the vector constructor. See example here: https://github.com/ddemidov/vexcl/blob/366411365bad007c216f353b61156154904c3041/tests/tensordot.cpp#L27-L32.

**Comment by acterhd** [comment]
Need all devices - one data.

2016-01-03 21:01 GMT+08:00 Denis Demidov <notifications@github.com>:

**Comment by acterhd** [comment]
Aaaa..... I forget atomics!

2016-01-03 21:03 GMT+08:00 Alexey Solovey <acterhd@gmail.com>:

**Comment by ddemidov** [comment]
There is no way to do this in VexCL. As a workaround, you could create a copy of the vector per device. No idea what atomics have to do with this :).

**Comment by acterhd** [comment]
Okay :(
I probably don't will use VexCL, for me need been virtual shared memory.
I like original C++ OpenCL wrapper.


2016-01-03 21:07 GMT+08:00 Denis Demidov <notifications@github.com>:
