### ISSUE TITLE
OpenCL 2.0 support

### ISSUE THREAD

**Issue by jdumas** [ddemidov/vexcl#198]
Hi,

I noticed you have switched to OpenCL 2.0 headers recently. However, on Nvidia GPUs we are still stuck to OpenCL 1.2 if I remember correctly. Do you plan to support both? This would be useful if one plan to use VexCL with only the OpenCL backend in mind (e.g. using custom kernels, but maintaining interoperability because it's still OpenCL). I'm not sure how it all works at the moment.

On a side note, I don't understand why you also keep a copy of the OpenCL headers in the source tree? In the CMakeLists.txt the `find_package` will give you the system-wide location of the OpenCL headers, so it might conflict with the one in the source-tree of VexCL?

**Comment by ddemidov** [comment]
`cl2.hpp` provides support for several versions of the specification. VexCL by default [asks for OpenCL 1.2](https://github.com/ddemidov/vexcl/blob/master/vexcl/backend/opencl/defines.hpp#L5). It does work for me with AMD (2.0), NVIDIA (1.2), and Intel (1.2) platforms.

> why you also keep a copy of the OpenCL headers in the source tree?

Some distributions only include C API headers. So the C++ headers are included for convenience. It should not be a problem if those are also present in the system include dirs, the compiler would pick the first one it sees.

**Comment by jdumas** [comment]
Ah, I see, thanks!
Turns out the problem I had was coming from ViennaCL, which includes OpenCL 1.1 in its source tree. As I had both VexCL and ViennaCL in my project (for testing purpose), the compiler was including `cl.hpp` (1.1) from ViennaCL and `cl2.hpp` from VexCL (1.2), hence my confusion (I was getting compiler errors).

**Comment by ddemidov** [comment]
I guess one could also define the appropriate macro to trigger cl.hpp include guard and effectively skip it.
