### ISSUE TITLE
Multiple custom kernels?

### ISSUE THREAD

**Issue by gcarvajalb** [ddemidov/vexcl#200]
Hi there,

this may be a very basic question, but I've been checking the examples and the source code, and all code I've seen so far using custom kernels contain only one kernel in the source like this:

```
const char source[] = VEX_STRINGIZE_SOURCE(
    		kernel void kernel1( arguments )
			{ kernel1 body}
); 
...

//compile program and create kernel
vex::backend::kernel kernel1_alias(ctx.queue(0), source, "kernel1");
...

kernel1_alias(ctx.queue(0),  .... arguments );
```

Is it possible to have multiple custom kernels? If so, how do I do it?  
For example, using a source like this:

```
const char source[] = VEX_STRINGIZE_SOURCE(
                     kernel void kernel1()
		             { kernel1 body}
                     kernel void kernel2()
                     { kernel2 body}
); 
```

I'd need to call kernel1 and kernel2 in different places of my program. I've been digging examples and docs and I've been unable to figure it out.

Thanks!

**Comment by Reneg973** [comment]
I've added an additional constructor taking a cl:: program instead of a source string and build options.

**Comment by ddemidov** [comment]
I think it should be possible to expose program objects to the user. Then something like this should work:
```cpp
auto program = vex::backend::build_sources(queue, source);
vex::backend::kernel K1(program, "K1");
vex::backend::kernel K2(program, "K2");
```
I'll look into this.

But for now, you could just split the source so that each chunk contains single kernel, and compile those separately. The overhead should not be too high, as vexcl creates single program/kernel per expression anyway.

**Comment by gcarvajalb** [comment]
@ddemidov:  thanks. For some reason I never thought on splitting the kernels and compile them separately. I was assuming I could only call the compilation once in the program, but as you mention every expression generates a kernel anyway. The overhead is not really critical at this point. I guess I was confused with the practice of generating the program from a single .cl file in bare OpenCL.

@Reneg973 : could you provide a simple example on how to use that constructor?

Thanks to both of you for the answers.

**Comment by ddemidov** [comment]
a8ba4c4 exposes `vex::backend::program` and allows to create several kernels with a single program. See [tests/custom_kernel.cpp](https://github.com/ddemidov/vexcl/blob/master/tests/custom_kernel.cpp) for examples.

**Comment by gcarvajalb** [comment]
Thanks a lot.

Both approaches (compiling kernels individually and the vex::backend::program) are working.

**Comment by ddemidov** [comment]
Thanks for reporting back! I'll close this then.
