### ISSUE TITLE
Symbolic example giving unexpected results

### ISSUE THREAD

**Issue by agerlach** [ddemidov/vexcl#201]
When I run the symbolic.cpp example it appears as if no actual work is performed by the kernel. the output is always the initial condition of the system. Changing the output lines at the end of symbolic.cpp to
```cpp
vex::copy( X , result );
for (int ii = 0; ii < n; ++ii){
     cout << result[ii] endl;
}
```
prints the initial condition for X for all realizations of the system. Am I missing something here? 

Thanks!

**Comment by ddemidov** [comment]
Thanks for catching that! Should be fixed by 81a7dfb.

**Comment by agerlach** [comment]
Thanks, looks good! I used vexCL a little over 2 years ago and I am really impressed by how your project has matured since then (I was impressed at that time too!). I'm really interested in leveraging it for a new project I'm on. I hope you don't mind if I send you some questions.

**Comment by ddemidov** [comment]
Thanks!

>  I hope you don't mind if I send you some questions.

Sure.
