### ISSUE TITLE
Segfault when compiling with AddressSanitizer

### ISSUE THREAD

**Issue by jdumas** [ddemidov/vexcl#204]
When I compile the "[hello world](http://vexcl.readthedocs.io/en/latest/initialize.html)" example from the documentation, with the compiler option `-fsanitize=address`, I get the following runtime error:

    terminate called after throwing an instance of 'cl::Error'
      what():  clGetPlatformIDs

I'm compiling the code with the following options:

    g++ main.cpp -DVEXCL_BACKEND_OPENCL -isystem ~/external/git/vexcl  -fsanitize=address -std=c++11 -lboost_system -lboost_filesystem -lOpenCL

On the other hand, creating a single OpenCL context without `vexcl` works fine with the option `-fsanitize=address`. I observe this behavior both under gcc 5.3.0 and clang 3.7.1. I'm not sure what's causing the issue =/

**Comment by ddemidov** [comment]
My guess is that this is just a bug/limitation of the address sanitizer when used with GPU drivers. For example, valgrind always finds problem in OpenCL/CUDA executables (for example, see [here](https://streamcomputing.eu/blog/2014-06-05/valgrind-suppression-file-amd64-linux/) and [here](https://devtalk.nvidia.com/default/topic/456438/valgrind-seems-to-be-showing-a-lot-of-errors-with-driver/)). It look like the address sanitizer has similar problems.

**Comment by ddemidov** [comment]
I get same problem when using `-fsanitize=address` with [this](https://gist.github.com/ddemidov/2925717) native OpenCL example. So the problem is either in OpenCL drivers or in sanitizer implementation.

**Comment by jdumas** [comment]
Ok, I thought OpenCL was not the culprit since I was able to create a `cl::Context` getting any error. However, the problem seems to lie in the function `cl::Platform::get` (and its call to `clGetPlatformIDs`). I'm not sure whether this is a bug in AddressSanitizer, or the OpenCL headers, but at least it's not an issue with VexCL =)
