### ISSUE TITLE
Compilation error boost 1.62

### ISSUE THREAD

**Issue by skn123** [ddemidov/vexcl#209]
Error log
[ 76%] Building CXX object tests/CMakeFiles/boost_compute_scan.dir/boost_compute_scan.cpp.o
In file included from /home/naths/srcs/vexcl/tests/boost_compute_scan.cpp:4:0:
/home/naths/srcs/vexcl/vexcl/external/boost_compute.hpp: In instantiation of ‘void vex::compute::inclusive_scan(const vex::vector<T>&, vex::vector<T>&) [with T = double]’:
/home/naths/srcs/vexcl/tests/boost_compute_scan.cpp:16:38:   required from here
/home/naths/srcs/vexcl/vexcl/external/boost_compute.hpp:65:41: error: no matching function for call to ‘scan(boost::compute::buffer_iterator<double>, boost::compute::buffer_iterator<double>, boost::compute::buffer_iterator<double>, bool, boost::compute::command_queue&)’
             boost::compute::detail::scan(
                                         ^
In file included from /usr/local/include/boost/compute/algorithm/exclusive_scan.hpp:17:0,
                 from /usr/local/include/boost/compute/algorithm/transform_if.hpp:19,
                 from /usr/local/include/boost/compute/algorithm/copy_if.hpp:14,
                 from /usr/local/include/boost/compute/algorithm.hpp:25,
                 from /usr/local/include/boost/compute.hpp:14,
                 from /home/naths/srcs/vexcl/vexcl/external/boost_compute.hpp:37,
                 from /home/naths/srcs/vexcl/tests/boost_compute_scan.cpp:4:
/usr/local/include/boost/compute/algorithm/detail/scan.hpp:23:23: note: candidate: template<class InputIterator, class OutputIterator, class T, class BinaryOperator> OutputIterator boost::compute::detail::scan(InputIterator, InputIterator, OutputIterator, bool, T, BinaryOperator, boost::compute::command_queue&)
 inline OutputIterator scan(InputIterator first,
                       ^
/usr/local/include/boost/compute/algorithm/detail/scan.hpp:23:23: note:   template argument deduction/substitution failed:
In file included from /home/naths/srcs/vexcl/tests/boost_compute_scan.cpp:4:0:
/home/naths/srcs/vexcl/vexcl/external/boost_compute.hpp:65:41: note:   candidate expects 7 arguments, 5 provided
             boost::compute::detail::scan(
                                         ^
/home/naths/srcs/vexcl/vexcl/external/boost_compute.hpp: In instantiation of ‘void vex::compute::exclusive_scan(const vex::vector<T>&, vex::vector<T>&) [with T = double]’:
/home/naths/srcs/vexcl/tests/boost_compute_scan.cpp:34:38:   required from here
/home/naths/srcs/vexcl/vexcl/external/boost_compute.hpp:125:41: error: no matching function for call to ‘scan(boost::compute::buffer_iterator<double>, boost::compute::buffer_iterator<double>, boost::compute::buffer_iterator<double>, bool, boost::compute::command_queue&)’
             boost::compute::detail::scan(
                                         ^
In file included from /usr/local/include/boost/compute/algorithm/exclusive_scan.hpp:17:0,
                 from /usr/local/include/boost/compute/algorithm/transform_if.hpp:19,
                 from /usr/local/include/boost/compute/algorithm/copy_if.hpp:14,
                 from /usr/local/include/boost/compute/algorithm.hpp:25,
                 from /usr/local/include/boost/compute.hpp:14,
                 from /home/naths/srcs/vexcl/vexcl/external/boost_compute.hpp:37,
                 from /home/naths/srcs/vexcl/tests/boost_compute_scan.cpp:4:
/usr/local/include/boost/compute/algorithm/detail/scan.hpp:23:23: note: candidate: template<class InputIterator, class OutputIterator, class T, class BinaryOperator> OutputIterator boost::compute::detail::scan(InputIterator, InputIterator, OutputIterator, bool, T, BinaryOperator, boost::compute::command_queue&)
 inline OutputIterator scan(InputIterator first,
                       ^
/usr/local/include/boost/compute/algorithm/detail/scan.hpp:23:23: note:   template argument deduction/substitution failed:
In file included from /home/naths/srcs/vexcl/tests/boost_compute_scan.cpp:4:0:
/home/naths/srcs/vexcl/vexcl/external/boost_compute.hpp:125:41: note:   candidate expects 7 arguments, 5 provided
             boost::compute::detail::scan(
                                         ^
cc1plus: warning: unrecognized command line option ‘-Wno-ignored-attributes’
tests/CMakeFiles/boost_compute_scan.dir/build.make:62: recipe for target 'tests/CMakeFiles/boost_compute_scan.dir/boost_compute_scan.cpp.o' failed
make[2]: *** [tests/CMakeFiles/boost_compute_scan.dir/boost_compute_scan.cpp.o] Error 1
CMakeFiles/Makefile2:1378: recipe for target 'tests/CMakeFiles/boost_compute_scan.dir/all' failed
make[1]: *** [tests/CMakeFiles/boost_compute_scan.dir/all] Error 2
Makefile:138: recipe for target 'all' failed

**Comment by ddemidov** [comment]
Thanks for reporting, this should be fixed by 53a3a95.
