### ISSUE TITLE
fast one dimensional discrete laplace operator on complex data type

### ISSUE THREAD

**Issue by magashegyi** [ddemidov/vexcl#211]
Hy.I want to compute a -d*(d/dx)^2 psi expression. The discrete version of this is 2.0*d*psi[i]-d*(psi[i-1]+psi[i+1] where i is the element index of the psi, the d is a double variable, psi is cl_double2 variable (because as i know there is no complex<double> variable in vexcl). First time i tried to write it as a tridiagonal matrix-vector multiplication with vex::SpMat but I'm having trouble in this way. Secondly i tried to implement it based on this example: http://vexcl.readthedocs.io/en/latest/expressions.html. 
My implementation is:
```cpp
VEX_FUNCTION(cl_double2, Ham0, (size_t, n)(size_t, i)(double, d)(cl_double2*, psi),
            double2 ham0_psi;

            if(i==0)
                ham0_psi =  2.0*d*psi[i]-d*psi[i+1];
            else if(i==n-1)
                ham0_psi =  2.0*d*psi[i]-d*psi[i-1];
            else
                ham0_psi =  2.0*d*psi[i]-d*(psi[i-1]+psi[i+1]);

            return ham0_psi;
        );
```
I'm newbie in GPU computing and OpenCL. My question is can I implement this problem in a more efficient way? Thanks in advance! (Sorry for my pure english)

**Comment by ddemidov** [comment]
Your implementation is exactly how I would do this. You could try to slightly improve efficiency by using cooperative read into a local memory array first, then computing `ham0_psi` from that, but given that you only read neighboring values, and that modern GPUs have automatic caches, I don't think you'll get  much out of this.

**Comment by magashegyi** [comment]
Thanks for your reply! I have one more question. I have more than 9 parameters in some VEX_FUNCTION and it's give me a compile error, but more of these parameters do not change at kernels runtime. I tried to use these parameters as a normal global parameter in c++ and define with VEX_CONSTANT but it don't works. So my question is that possible to define for example a d variable and use it in several VEX_FUNCTION for example this way

global double d

VEX_FUNCTION(cl_double2, ham0, (size_t, n)(size_t, i)(cl_double2*, psi),

            double2 ham0_psi;

            if(i==0)
                ham0_psi =  2.0*d*psi[i]-d*psi[i+1];
            else if(i==n-1)
                ham0_psi =  2.0*d*psi[i]-d*psi[i-1];
            else
                ham0_psi =  2.0*d*psi[i]-d*(psi[i-1]+psi[i+1]);
            return ham0_psi;
        );

VEX_FUNCTION(cl_double2, ham1, (size_t, n)(size_t, i)(cl_double2*, psi),

            double2 ham1_psi;

            if(i==0)
                ham1_psi =  2.0*d*psi[i]-d*psi[i+1];
            else if(i==n-1)
                ham1_psi =  2.0*d*psi[i]-d*psi[i-1];
            else
                ham1_psi =  2.0*d*psi[i]-d*(psi[i-1]+psi[i+1]);
            return ham1_psi;
        );

(I hope it's clear what i want to do) Thanks in advance!

**Comment by ddemidov** [comment]
> I have more than 9 parameters in some VEX_FUNCTION and it's give me a compile error

This is a limitation of boost.proto. You can increase the limit by declaring `BOOST_PROTO_MAX_ARITY` macro, for example with `-DBOOST_PROTO_MAX_ARITY=15` (try to keep this as low as possible though, as it increases compile time).

>  is that possible to define for example a d variable

You can provide custom headers for the generated device code with [`vex::push_program_header()`](https://github.com/ddemidov/vexcl/blob/53a3a959164f396970c6e745981453f78ea80c66/vexcl/backend/common.hpp#L154-L158) function. Example:

```c++
std::ostringstream h;
h << "double d = " << d << std::endl;
vex::push_program_header(ctx, h.str());
```

**Comment by magashegyi** [comment]
The last solution is suitable for me! The 
            std::ostringstream h;
            h << "__constant double d = " << d <<";"<< std::endl;
            vex::push_program_header(ctx, h.str());

seems to be working! Thanks a lot!
