### ISSUE TITLE
how to read Video

### ISSUE THREAD

**Issue by jackweiwang** [ddemidov/vexcl#221]
I want to read a video using vexcl, an example which is better, how do I modify it?

thank you!

**Comment by ddemidov** [comment]
I am not sure what exactly is that you want. If you want to read a videofile or a videostream as a series of frames, and then process it with vexcl, then you need a library that can read the specific video format and transform it to an array of numbers. VexCL can not help you here.

**Comment by jackweiwang** [comment]
Images can also be, image data can be processed by Vexcl?I hope is to process images (such as weighted), because compared vexcl opencl will be much convenient, I can use an example?

I saw a closed question, it is said the picture, but there is no help to me.

**Comment by ddemidov** [comment]
Anything that you can convert to an array of numbers can be processed by vexcl, but you will need to come up with a way to convert an image to an array of numbers first. You can use a third party library for that, for example http://www.graphicsmagick.org/. VexCL itself has no functionality for image/video input-output.

**Comment by jackweiwang** [comment]
i see, very thankful
