### ISSUE TITLE
Odd CMake version

### ISSUE THREAD

**Issue by henryiii** [ddemidov/vexcl#223]
I've noticed that you've listed a non-existent version of CMake, 2.9, as the minimum version. Since that makes the minimum 3.0, actually setting 3.0 is better since it fixes a lot of defaults, like the macOS RPATH default. (Note: CMake selects policies based on that value).

Just a suggestion.

**Comment by ddemidov** [comment]
Thanks for spotting that. I think I bumped it to 2.9 for a [reason](57a285dca3eb778a510f928109eec799adaf7f99), but not sure what the reason was exactly :).
