### ISSUE TITLE
Bump CMake version (fixes problems)

### ISSUE THREAD

**Issue by henryiii** [ddemidov/vexcl#224]
I'm preparing a PR with some fixes for the Mac build, along with a couple of helper functions for setting up multiple targets in CMake. Along those lines, I'd like to bump up the CMake version at least to 3.1. In my case, I need it to fix the C++11 selection (which is hardcoded and incorrect at 0x currently). Here are the benefits for different CMake versions:

* 3.0: Adds the `::` targets VexCL currently uses heavily, first version to properly support macOS (if min 3.0 or higher set)
* 3.1: Adds C++11 support, both through global setting and compiler features
* 3.3: IN_LIST added
* 3.7: Adds a much better FindCUDA, including target architecture discovery
* 3.8: Meta compiler-features (cxx11, cxx14, and cxx17), and CUDA added as a first-class language, alongside C, CXX, and FORTRAN. (I believe these are finally handled correctly with CUDA, before it was a separate variable)
* 3.9: Current version, improvements for CUDA on Windows

I'd really like to bump the version required to at least 3.1 (many scientific packages, like CERN's ROOT, are on 3.3 or 3.4 now). It's one line to install CMake almost anywhere, and can be done without admin privileges. (`pip install --user cmake` often works fine), so let me know if I could set it to a higher version in the PR.

My proposal is to use [compiler features](https://cmake.org/cmake/help/v3.1/prop_gbl/CMAKE_CXX_KNOWN_FEATURES.html#prop_gbl:CMAKE_CXX_KNOWN_FEATURES) from 3.1, which will allow 0x or 11 to be selected, and even overridden by users. (Help in listing the C++11 features VexCL uses appreciated ;) )

Also adding a few typo corrections to docs and example in docs.

**Comment by ddemidov** [comment]
This sounds nice, thanks for working on it! I am ok with bumping cmake to 3.1.

> Help in listing the C++11 features VexCL uses appreciated

VexCL is compatible with VS2010, so that dictates [the list of acceptable C++11 features](https://blogs.msdn.microsoft.com/vcblog/2010/04/06/c0x-core-language-features-in-vc10-the-table/).
