### ISSUE TITLE
Enable MacOS tests on Travis-CI

### ISSUE THREAD

**Issue by ddemidov** [ddemidov/vexcl#228]
The way it's done in boost.compute should be a good starting point: https://github.com/boostorg/compute/blob/d36ef02b7860b9bcf5ea4911b77f1aa77b5f4059/.travis.yml#L355-L358

**Comment by henryiii** [comment]
macOS testing in Travis is easy, though Travis's macOS builds get behind occasionally. They provide brew automatically, so Boost, CMake, etc. are really easy to get.

**Comment by ddemidov** [comment]
If you have some experience with this, would you care to provide a PR? Otherwise, I'll try to do this later.

**Comment by ddemidov** [comment]
Resolved by #230
