### ISSUE TITLE
add typedef T* mapped_pointer in  vexcl/vexcl/backend/cuda/svm_vector.hpp

### ISSUE THREAD

**Issue by mingwugmail** [ddemidov/vexcl#234]
add typedef T* mapped_pointer in 

 vexcl/vexcl/backend/cuda/svm_vector.hpp

So the library user can just use:

vex::svm_vector<XXX>::mapped_pointer as a type, regardless of which backend (opencl, cuda) he's using.

**Comment by ddemidov** [comment]
Done. Thanks for pointing that out (but why is this an issue and not a pull request? :wink:)
