### ISSUE TITLE
examples/CMakeLists.txt is missing add_definitions(-std=c++11)

### ISSUE THREAD

**Issue by yurivict** [ddemidov/vexcl#239]
clang build fails without it.

**Comment by ddemidov** [comment]
That is strange, because these lines in `CMakeLists.txt`should make sure that at least C++11 standard is used:

https://github.com/ddemidov/vexcl/blob/e2f3643bae7caf7ba5f00a3a92558297656758ca/CMakeLists.txt#L53-L61

Also, Travis-CI builds are successful both for G++ and Clang.

**Comment by yurivict** [comment]
Sorry, I've ran cmake in the ```examples/``` directory.
