### ISSUE TITLE
at() for vectors

### ISSUE THREAD

**Issue by henryiii** [ddemidov/vexcl#241]
The `at()` method is missing for vectors. Keeping as much of the API consistent for the standard library as possible would be nice!

**Comment by ddemidov** [comment]
It would be easy to implement in terms of `vector::operator[]`:

https://github.com/ddemidov/vexcl/blob/e2f3643bae7caf7ba5f00a3a92558297656758ca/vexcl/vector.hpp#L586-L599

Would you like to provide a pull request?

**Comment by henryiii** [comment]
Sure, though might be early next week.
