### ISSUE TITLE
CMake boost version detection failed on recent boost

### ISSUE THREAD

**Issue by UNDEFINED-BEHAVIOR** [ddemidov/vexcl#278]
Current boost version detection in cmakelist, here,
https://github.com/ddemidov/vexcl/blob/c8a3ebd0b746c7595b19c3cd47a03e97f9d9c5db/CMakeLists.txt#L144
Is expecting string such as
`"106100"`
To perform comparison but actual Boost_VERSION (as showed up in debug print) turns out to be in this format.
`1.73.0`
I have to disable this check to get compute back end to be available.

**Comment by ddemidov** [comment]
Thanks! 9814c4b should fix this.

**Comment by UNDEFINED-BEHAVIOR** [comment]
The fix works, thanks.
closing the ticket now.
