### ISSUE TITLE
boost compute question

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [ddemidov/vexcl#281]
I'm making an ebuild for ::guru overlay. What does `VEXCL_HAVE_BOOST_COMPUTE` do? Is it used to _add_ Boost.Compute algorithms to other backends?

**Comment by ddemidov** [comment]
Looks like it only enables some additional benchmarks (using algorithms from Boost.compute) in the `examples/benchmark.cpp`:

https://github.com/ddemidov/vexcl/search?q=VEXCL_HAVE_BOOST_COMPUTE

**Comment by Alessandro-Barbieri** [comment]
ok, thanks

You can see my updated ebuild here https://github.com/gentoo/guru/tree/dev/dev-cpp/vexcl
