### ISSUE TITLE
Linking Issue!!

### ISSUE THREAD

**Issue by kafi350** [ddemidov/vexcl#285]
Hello,

I was trying to link vexCL with and existing OpenCL project and it fails whenever i do the 
#include <vexcl/vexcl.hpp>

I am attaching the error in a text file. 

[Error.txt](https://github.com/ddemidov/vexcl/files/6868396/Error.txt)

Please let me know what's actually the issue as I tried almost all ways possible to resolve it.

**Comment by ddemidov** [comment]
It does not look like a linking error, it fails to compile judging by the log you attached.

How exactly are you building the project (command line with all the flags)? Can you reproduce the same issue with a minimal compilable example and post is here (again, both source code and the command line you use for building)?

**Comment by ddemidov** [comment]
The log says `cl::Error` type is undefined, but it should come from `<CL/cl.hpp>`, which should come from your OpenCL SDK (it is also provided at https://github.com/ddemidov/vexcl/tree/master/CL for convenience).

**Comment by kafi350** [comment]
![lol](https://user-images.githubusercontent.com/20300450/126988428-25663a4c-22ae-413b-a6ed-6b640c102b32.png)

Even If I try the normal initialization of VexCL the same error occurs.

**Comment by ddemidov** [comment]
Try to define the preprocessor macro `CL_TARGET_OPENCL_VERSION=120`.

**Comment by kafi350** [comment]
It worked without changing the version. 
I did a clean openCL installation and Boost.Compute installation. Now it is building.
Thank you!
