### ISSUE TITLE
Conversion (Casting) of  Vex Vector to Std::vector

### ISSUE THREAD

**Issue by kafi350** [ddemidov/vexcl#287]
Is it possible to change the vex::vector<int> type to std::vector?
I tried it several ways but could not do it.

**Comment by ddemidov** [comment]
`std::vector` and `vex::vector` live in completely different memory spaces (CPU vs GPU memory), so one can not be cast to another. You can copy the data between them: https://vexcl.readthedocs.io/en/latest/memory.html#copying

Or you can do something like this if you need to:
```cpp
template <class T>
std::vector<T> to_std_vector(const vex::vector<T> &v) {
  std::vector<T> s(v.size());
  vex::copy(v, s);
  return s;
}
```

**Comment by kafi350** [comment]
Thank you!
